In [1]:
import pandas as pd

In [3]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [2]:
df = pd.read_csv("bugs.csv")
df.sample(5)

,Bug ID,Type,Summary,Product,Component,Assignee,Status,Resolution,Updated
3442,1769005,task,Write a Testing & Rollout plan,Data Platform and Tools,Glean: SDK,jrediger,RESOLVED,FIXED,2022-06-20 05:42:04
138,1941053,enhancement,Adding Solo to More from Mozilla - Land strings,Firefox,Messaging System,halemu,RESOLVED,FIXED,2025-02-05 12:38:09
2234,1644110,enhancement,Resource usage artifacts and Taskcluster ETL,Data Platform and Tools,General,mtrinkala,RESOLVED,FIXED,2022-07-26 12:19:37
7644,1699264,defect,Can't add new browsertime tasks to try run thr...,Testing,Raptor,gmierz2,RESOLVED,FIXED,2021-03-18 14:41:19
2280,1806792,task,"Implement ""input.releaseActions"" command",Remote Protocol,WebDriver BiDi,aborovova,RESOLVED,FIXED,2023-05-02 04:52:29

In [3]:
len(df['Bug ID'].unique())

10000

In [ ]:
len(df)

10000

In [5]:
len(df[df.duplicated()])

0

In [11]:
df[df.duplicated()]

,author,creation_time,bug_id,text,Bug report,author_id,status,resolution,contains_steps_to_reproduce
1,itiel_yn8@walla.com,2022-11-19T21:20:37Z,1801502,created attachment 9304261screenshotthis is es...,True,353822.0,VERIFIED,FIXED,False
8,egorgrits@gmail.com,2022-11-19T17:03:32Z,1801488,created attachment 9304242debian_bullseye_bug_...,True,717346.0,RESOLVED,FIXED,True
9,egorgrits@gmail.com,2022-11-19T17:03:32Z,1801488,created attachment 9304242debian_bullseye_bug_...,True,717346.0,RESOLVED,FIXED,True
10,egorgrits@gmail.com,2022-11-19T17:03:32Z,1801488,created attachment 9304242debian_bullseye_bug_...,True,717346.0,RESOLVED,FIXED,True
12,nerli@mozilla.com,2022-11-19T12:54:41Z,1801479,[tracking requested - why for this release]:- ...,True,600656.0,VERIFIED,FIXED,False
...,...,...,...,...,...,...,...,...,...
71075,dave.hunt@gmail.com,2021-03-28T17:07:50Z,1701511,we currently attempt to install the visual met...,True,396948.0,RESOLVED,FIXED,False
71076,dave.hunt@gmail.com,2021-03-28T17:07:50Z,1701511,we currently attempt to install the visual met...,True,396948.0,RESOLVED,FIXED,False
71078,dietrich@webtransitions.org,2021-03-28T16:54:32Z,1701510,created attachment 9212061screen shot 2021-03-...,True,213632.0,RESOLVED,FIXED,False
71079,dietrich@webtransitions.org,2021-03-28T16:54:32Z,1701510,created attachment 9212061screen shot 2021-03-...,True,213632.0,RESOLVED,FIXED,False
71080,dietrich@webtransitions.org,2021-03-28T16:54:32Z,1701510,created attachment 9212061screen shot 2021-03-...,True,213632.0,RESOLVED,FIXED,False

In [ ]:
final_status_df = df.drop_duplicates().sort_values('creation_time').groupby('bug_id').last().reset_index()

In [13]:
print(final_status_df)

        bug_id                 author         creation_time  \
0      1689124   wlach@protonmail.com  2021-01-27T15:34:41Z
1      1689126  cpeterson@mozilla.com  2021-01-27T15:42:54Z
2      1689128  bobowencode@gmail.com  2021-01-27T15:51:35Z
3      1689131       nhnt11@gmail.com  2021-01-27T16:06:03Z
4      1689136  bobowencode@gmail.com  2021-01-27T16:28:26Z
...        ...                    ...                   ...
83545  1931479     update-bot@bmo.tld  2024-11-15T06:31:58Z
83546  1931480    ajoltan@mozilla.com  2024-11-15T07:02:04Z
83547  1931481    ajoltan@mozilla.com  2024-11-15T07:12:31Z
83548  1931493      chenx97@gmail.com  2024-11-15T09:10:14Z
83549  1931496        jwatt@jwatt.org  2024-11-15T09:20:03Z

                                                    text  Bug report  \
0      there are multiple options for scheduling quer...        True
1      a crash event can have no report payload if th...        True
2      this was introduced in windows 10 and was turn...        True
3      please change the triage owner for "firefox ::...        True
4      this is a defence in depth for things that are...        True
...                                                  ...         ...
83545  this update covers 1 commits. here are the ove...        True
83546  add missing site permissions assertion in ui t...        True
83547  add missing "edit" assertion to the top sites ...        True
83548  steps to reproduce:build firefox natively on m...        True
83549  i just noticed some missed instances of this i...        True

       author_id    status resolution  contains_steps_to_reproduce
0       420096.0  RESOLVED      FIXED                        False
1       430528.0  RESOLVED      FIXED                        False
2       458623.0  RESOLVED      FIXED                        False
3       481547.0  RESOLVED      FIXED                        False
4       458623.0  RESOLVED      FIXED                        False
...          ...       ...        ...                          ...
83545   675523.0  RESOLVED      FIXED                        False
83546   635758.0  RESOLVED      FIXED                        False
83547   635758.0  RESOLVED      FIXED                        False
83548   763464.0  RESOLVED      FIXED                         True
83549    32767.0  RESOLVED      FIXED                        False

[83550 rows x 9 columns]

In [14]:
df['resolution'].value_counts()

resolution
FIXED    119585
Name: count, dtype: int64

In [7]:

df['Status'].value_counts()

Status
RESOLVED    9990
CLOSED        10
Name: count, dtype: int64

In [6]:

df['Status'].unique()

<StringArray>
['RESOLVED', 'CLOSED']
Length: 2, dtype: str