In [1]:
import pandas as pd

In [3]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [4]:
df = pd.read_excel("100k_filtered_raw_bug_reports.xlsx")
df.sample(5)

,author,creation_time,bug_id,text,Bug report,author_id,status,resolution,contains_steps_to_reproduce
42970,wptsync@mozilla.bugs,2021-06-18T14:35:26Z,1717219,sync web-platform-tests pr 29433 into mozilla-...,True,611017.0,RESOLVED,FIXED,False
28597,wptsync@mozilla.bugs,2021-08-05T23:39:52Z,1724328,sync web-platform-tests pr 29924 into mozilla-...,True,611017.0,RESOLVED,FIXED,False
20044,wptsync@mozilla.bugs,2021-08-30T10:47:43Z,1728088,sync web-platform-tests pr 30226 into mozilla-...,True,611017.0,RESOLVED,FIXED,False
33257,bytesized@mozilla.com,2021-07-23T21:49:25Z,1722098,str: 1. download the fzf binary and copy it to...,True,563604.0,RESOLVED,FIXED,False
58734,lhansen@mozilla.com,2021-04-30T16:16:36Z,1708743,we should experiment with avx2 support for sim...,True,499633.0,RESOLVED,FIXED,False

In [5]:
len(df['bug_id'].unique())

83550

In [6]:
len(df)

119585

In [9]:
len(df[df.duplicated()])

36034

In [11]:
df[df.duplicated()]

,author,creation_time,bug_id,text,Bug report,author_id,status,resolution,contains_steps_to_reproduce
1,itiel_yn8@walla.com,2022-11-19T21:20:37Z,1801502,created attachment 9304261screenshotthis is es...,True,353822.0,VERIFIED,FIXED,False
8,egorgrits@gmail.com,2022-11-19T17:03:32Z,1801488,created attachment 9304242debian_bullseye_bug_...,True,717346.0,RESOLVED,FIXED,True
9,egorgrits@gmail.com,2022-11-19T17:03:32Z,1801488,created attachment 9304242debian_bullseye_bug_...,True,717346.0,RESOLVED,FIXED,True
10,egorgrits@gmail.com,2022-11-19T17:03:32Z,1801488,created attachment 9304242debian_bullseye_bug_...,True,717346.0,RESOLVED,FIXED,True
12,nerli@mozilla.com,2022-11-19T12:54:41Z,1801479,[tracking requested - why for this release]:- ...,True,600656.0,VERIFIED,FIXED,False
...,...,...,...,...,...,...,...,...,...
71075,dave.hunt@gmail.com,2021-03-28T17:07:50Z,1701511,we currently attempt to install the visual met...,True,396948.0,RESOLVED,FIXED,False
71076,dave.hunt@gmail.com,2021-03-28T17:07:50Z,1701511,we currently attempt to install the visual met...,True,396948.0,RESOLVED,FIXED,False
71078,dietrich@webtransitions.org,2021-03-28T16:54:32Z,1701510,created attachment 9212061screen shot 2021-03-...,True,213632.0,RESOLVED,FIXED,False
71079,dietrich@webtransitions.org,2021-03-28T16:54:32Z,1701510,created attachment 9212061screen shot 2021-03-...,True,213632.0,RESOLVED,FIXED,False
71080,dietrich@webtransitions.org,2021-03-28T16:54:32Z,1701510,created attachment 9212061screen shot 2021-03-...,True,213632.0,RESOLVED,FIXED,False

In [ ]:
final_status_df = df.drop_duplicates().sort_values('creation_time').groupby('bug_id').last().reset_index()

In [13]:
print(final_status_df)

        bug_id                 author         creation_time  \
0      1689124   wlach@protonmail.com  2021-01-27T15:34:41Z
1      1689126  cpeterson@mozilla.com  2021-01-27T15:42:54Z
2      1689128  bobowencode@gmail.com  2021-01-27T15:51:35Z
3      1689131       nhnt11@gmail.com  2021-01-27T16:06:03Z
4      1689136  bobowencode@gmail.com  2021-01-27T16:28:26Z
...        ...                    ...                   ...
83545  1931479     update-bot@bmo.tld  2024-11-15T06:31:58Z
83546  1931480    ajoltan@mozilla.com  2024-11-15T07:02:04Z
83547  1931481    ajoltan@mozilla.com  2024-11-15T07:12:31Z
83548  1931493      chenx97@gmail.com  2024-11-15T09:10:14Z
83549  1931496        jwatt@jwatt.org  2024-11-15T09:20:03Z

                                                    text  Bug report  \
0      there are multiple options for scheduling quer...        True
1      a crash event can have no report payload if th...        True
2      this was introduced in windows 10 and was turn...        True
3      please change the triage owner for "firefox ::...        True
4      this is a defence in depth for things that are...        True
...                                                  ...         ...
83545  this update covers 1 commits. here are the ove...        True
83546  add missing site permissions assertion in ui t...        True
83547  add missing "edit" assertion to the top sites ...        True
83548  steps to reproduce:build firefox natively on m...        True
83549  i just noticed some missed instances of this i...        True

       author_id    status resolution  contains_steps_to_reproduce
0       420096.0  RESOLVED      FIXED                        False
1       430528.0  RESOLVED      FIXED                        False
2       458623.0  RESOLVED      FIXED                        False
3       481547.0  RESOLVED      FIXED                        False
4       458623.0  RESOLVED      FIXED                        False
...          ...       ...        ...                          ...
83545   675523.0  RESOLVED      FIXED                        False
83546   635758.0  RESOLVED      FIXED                        False
83547   635758.0  RESOLVED      FIXED                        False
83548   763464.0  RESOLVED      FIXED                         True
83549    32767.0  RESOLVED      FIXED                        False

[83550 rows x 9 columns]

In [14]:
df['resolution'].value_counts()

resolution
FIXED    119585
Name: count, dtype: int64

In [15]:

df['status'].value_counts()

status
RESOLVED    106885
VERIFIED     12700
Name: count, dtype: int64

In [16]:

df['status'].unique()

<StringArray>
['VERIFIED', 'RESOLVED']
Length: 2, dtype: str

In [18]:
df[df.duplicated() == False]

,author,creation_time,bug_id,text,Bug report,author_id,status,resolution,contains_steps_to_reproduce
0,itiel_yn8@walla.com,2022-11-19T21:20:37Z,1801502,created attachment 9304261screenshotthis is es...,True,353822.0,VERIFIED,FIXED,False
2,0xgodson@gmail.com,2022-11-19T21:02:27Z,1801501,created attachment 9304259index.htmlbrowser us...,True,713322.0,RESOLVED,FIXED,True
3,emilio@crisal.io,2022-11-19T20:58:00Z,1801500,as per comments there.,True,546716.0,RESOLVED,FIXED,False
4,wptsync@mozilla.bugs,2022-11-19T20:48:45Z,1801498,sync web-platform-tests pr 37041 into mozilla-...,True,611017.0,RESOLVED,FIXED,False
5,mak@mozilla.com,2022-11-19T19:42:23Z,1801495,vfs on top of the -none ones to implement immu...,True,240353.0,RESOLVED,FIXED,False
...,...,...,...,...,...,...,...,...,...
119580,redlibrepy@gmail.com,2022-11-20T00:43:27Z,1801521,user agent: mozilla/5.0 (windows nt 10.0; win6...,True,375332.0,RESOLVED,FIXED,True
119581,emilio@crisal.io,2022-11-20T00:09:18Z,1801517,NaN,True,546716.0,RESOLVED,FIXED,False
119582,itiel_yn8@walla.com,2022-11-19T23:15:52Z,1801515,str:1. install https://addons.mozilla.org/he/f...,True,353822.0,RESOLVED,FIXED,False
119583,itiel_yn8@walla.com,2022-11-19T23:08:00Z,1801514,created attachment 9304280screenshotthis is be...,True,353822.0,RESOLVED,FIXED,False
119584,ch4sys@gmail.com,2022-11-19T22:56:47Z,1801512,created attachment 93042792_fontsmoothinggamma...,True,717527.0,VERIFIED,FIXED,True

In [19]:
len(df[df.duplicated() == False])

83551

In [20]:
len(df[df.duplicated() == False]['bug_id'].unique())

83550